// Generated by gencpp from file dcl_slam/global_descriptor.msg
// DO NOT EDIT!


#ifndef DCL_SLAM_MESSAGE_GLOBAL_DESCRIPTOR_H
#define DCL_SLAM_MESSAGE_GLOBAL_DESCRIPTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dcl_slam
{
template <class ContainerAllocator>
struct global_descriptor_
{
  typedef global_descriptor_<ContainerAllocator> Type;

  global_descriptor_()
    : header()
    , index(0)
    , values()  {
    }
  global_descriptor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , index(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _index_type;
  _index_type index;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::dcl_slam::global_descriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcl_slam::global_descriptor_<ContainerAllocator> const> ConstPtr;

}; // struct global_descriptor_

typedef ::dcl_slam::global_descriptor_<std::allocator<void> > global_descriptor;

typedef boost::shared_ptr< ::dcl_slam::global_descriptor > global_descriptorPtr;
typedef boost::shared_ptr< ::dcl_slam::global_descriptor const> global_descriptorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcl_slam::global_descriptor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcl_slam::global_descriptor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcl_slam::global_descriptor_<ContainerAllocator1> & lhs, const ::dcl_slam::global_descriptor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.index == rhs.index &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcl_slam::global_descriptor_<ContainerAllocator1> & lhs, const ::dcl_slam::global_descriptor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcl_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::global_descriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::global_descriptor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::global_descriptor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::global_descriptor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::global_descriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::global_descriptor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcl_slam::global_descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f823b303f7c022fcb757cc77326186f";
  }

  static const char* value(const ::dcl_slam::global_descriptor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f823b303f7c022fULL;
  static const uint64_t static_value2 = 0xcb757cc77326186fULL;
};

template<class ContainerAllocator>
struct DataType< ::dcl_slam::global_descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcl_slam/global_descriptor";
  }

  static const char* value(const ::dcl_slam::global_descriptor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcl_slam::global_descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# keyFreature descriptor\n"
"Header header\n"
"\n"
"int32 index\n"
"\n"
"float32[] values\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dcl_slam::global_descriptor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcl_slam::global_descriptor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.index);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct global_descriptor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcl_slam::global_descriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcl_slam::global_descriptor_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "values: ";
    if (v.values.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.values[i]);
    }
    if (v.values.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCL_SLAM_MESSAGE_GLOBAL_DESCRIPTOR_H
