// Generated by gencpp from file dcl_slam/loop_info.msg
// DO NOT EDIT!


#ifndef DCL_SLAM_MESSAGE_LOOP_INFO_H
#define DCL_SLAM_MESSAGE_LOOP_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Transform.h>
#include <geometry_msgs/Transform.h>
#include <sensor_msgs/PointCloud2.h>
#include <geometry_msgs/Transform.h>

namespace dcl_slam
{
template <class ContainerAllocator>
struct loop_info_
{
  typedef loop_info_<ContainerAllocator> Type;

  loop_info_()
    : header()
    , robot0(0)
    , robot1(0)
    , index0(0)
    , index1(0)
    , noise(0.0)
    , init_yaw(0)
    , pose0()
    , pose1()
    , scan_cloud()
    , pose_between()  {
    }
  loop_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot0(0)
    , robot1(0)
    , index0(0)
    , index1(0)
    , noise(0.0)
    , init_yaw(0)
    , pose0(_alloc)
    , pose1(_alloc)
    , scan_cloud(_alloc)
    , pose_between(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _robot0_type;
  _robot0_type robot0;

   typedef int32_t _robot1_type;
  _robot1_type robot1;

   typedef int32_t _index0_type;
  _index0_type index0;

   typedef int32_t _index1_type;
  _index1_type index1;

   typedef float _noise_type;
  _noise_type noise;

   typedef int32_t _init_yaw_type;
  _init_yaw_type init_yaw;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _pose0_type;
  _pose0_type pose0;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _pose1_type;
  _pose1_type pose1;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _scan_cloud_type;
  _scan_cloud_type scan_cloud;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _pose_between_type;
  _pose_between_type pose_between;





  typedef boost::shared_ptr< ::dcl_slam::loop_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcl_slam::loop_info_<ContainerAllocator> const> ConstPtr;

}; // struct loop_info_

typedef ::dcl_slam::loop_info_<std::allocator<void> > loop_info;

typedef boost::shared_ptr< ::dcl_slam::loop_info > loop_infoPtr;
typedef boost::shared_ptr< ::dcl_slam::loop_info const> loop_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcl_slam::loop_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcl_slam::loop_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcl_slam::loop_info_<ContainerAllocator1> & lhs, const ::dcl_slam::loop_info_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot0 == rhs.robot0 &&
    lhs.robot1 == rhs.robot1 &&
    lhs.index0 == rhs.index0 &&
    lhs.index1 == rhs.index1 &&
    lhs.noise == rhs.noise &&
    lhs.init_yaw == rhs.init_yaw &&
    lhs.pose0 == rhs.pose0 &&
    lhs.pose1 == rhs.pose1 &&
    lhs.scan_cloud == rhs.scan_cloud &&
    lhs.pose_between == rhs.pose_between;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcl_slam::loop_info_<ContainerAllocator1> & lhs, const ::dcl_slam::loop_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcl_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::loop_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::loop_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::loop_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::loop_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::loop_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::loop_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcl_slam::loop_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1431bfa4497640b0a25a7c95cc6acc6";
  }

  static const char* value(const ::dcl_slam::loop_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1431bfa4497640bULL;
  static const uint64_t static_value2 = 0x0a25a7c95cc6acc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcl_slam::loop_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcl_slam/loop_info";
  }

  static const char* value(const ::dcl_slam::loop_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcl_slam::loop_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Loop Info\n"
"Header header\n"
"\n"
"int32 robot0\n"
"int32 robot1\n"
"int32 index0\n"
"int32 index1\n"
"float32 noise\n"
"int32 init_yaw\n"
"geometry_msgs/Transform pose0\n"
"geometry_msgs/Transform pose1\n"
"sensor_msgs/PointCloud2 scan_cloud\n"
"geometry_msgs/Transform pose_between\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::dcl_slam::loop_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcl_slam::loop_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot0);
      stream.next(m.robot1);
      stream.next(m.index0);
      stream.next(m.index1);
      stream.next(m.noise);
      stream.next(m.init_yaw);
      stream.next(m.pose0);
      stream.next(m.pose1);
      stream.next(m.scan_cloud);
      stream.next(m.pose_between);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct loop_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcl_slam::loop_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcl_slam::loop_info_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "index0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "index1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "noise: ";
    Printer<float>::stream(s, indent + "  ", v.noise);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "init_yaw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.init_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose0: ";
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.pose0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose1: ";
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.pose1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scan_cloud: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.scan_cloud);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_between: ";
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_between);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCL_SLAM_MESSAGE_LOOP_INFO_H
