// Generated by gencpp from file dcl_slam/neighbor_estimate.msg
// DO NOT EDIT!


#ifndef DCL_SLAM_MESSAGE_NEIGHBOR_ESTIMATE_H
#define DCL_SLAM_MESSAGE_NEIGHBOR_ESTIMATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dcl_slam
{
template <class ContainerAllocator>
struct neighbor_estimate_
{
  typedef neighbor_estimate_<ContainerAllocator> Type;

  neighbor_estimate_()
    : header()
    , receiver_id(0)
    , estimation_done(0)
    , initialized(0)
    , anchor_offset()
    , pose_id()
    , estimate()  {
    }
  neighbor_estimate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , receiver_id(0)
    , estimation_done(0)
    , initialized(0)
    , anchor_offset(_alloc)
    , pose_id(_alloc)
    , estimate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _receiver_id_type;
  _receiver_id_type receiver_id;

   typedef int8_t _estimation_done_type;
  _estimation_done_type estimation_done;

   typedef int8_t _initialized_type;
  _initialized_type initialized;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _anchor_offset_type;
  _anchor_offset_type anchor_offset;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _pose_id_type;
  _pose_id_type pose_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _estimate_type;
  _estimate_type estimate;





  typedef boost::shared_ptr< ::dcl_slam::neighbor_estimate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcl_slam::neighbor_estimate_<ContainerAllocator> const> ConstPtr;

}; // struct neighbor_estimate_

typedef ::dcl_slam::neighbor_estimate_<std::allocator<void> > neighbor_estimate;

typedef boost::shared_ptr< ::dcl_slam::neighbor_estimate > neighbor_estimatePtr;
typedef boost::shared_ptr< ::dcl_slam::neighbor_estimate const> neighbor_estimateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcl_slam::neighbor_estimate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcl_slam::neighbor_estimate_<ContainerAllocator1> & lhs, const ::dcl_slam::neighbor_estimate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.receiver_id == rhs.receiver_id &&
    lhs.estimation_done == rhs.estimation_done &&
    lhs.initialized == rhs.initialized &&
    lhs.anchor_offset == rhs.anchor_offset &&
    lhs.pose_id == rhs.pose_id &&
    lhs.estimate == rhs.estimate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcl_slam::neighbor_estimate_<ContainerAllocator1> & lhs, const ::dcl_slam::neighbor_estimate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcl_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::neighbor_estimate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::neighbor_estimate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::neighbor_estimate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "070b606f57d52fcad04bff2934c82ffb";
  }

  static const char* value(const ::dcl_slam::neighbor_estimate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x070b606f57d52fcaULL;
  static const uint64_t static_value2 = 0xd04bff2934c82ffbULL;
};

template<class ContainerAllocator>
struct DataType< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcl_slam/neighbor_estimate";
  }

  static const char* value(const ::dcl_slam::neighbor_estimate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# estimate\n"
"Header header\n"
"\n"
"int8 receiver_id\n"
"int8 estimation_done\n"
"int8 initialized\n"
"\n"
"float32[] anchor_offset\n"
"\n"
"int32[] pose_id\n"
"\n"
"float32[] estimate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dcl_slam::neighbor_estimate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.receiver_id);
      stream.next(m.estimation_done);
      stream.next(m.initialized);
      stream.next(m.anchor_offset);
      stream.next(m.pose_id);
      stream.next(m.estimate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct neighbor_estimate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcl_slam::neighbor_estimate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcl_slam::neighbor_estimate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "receiver_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.receiver_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estimation_done: ";
    Printer<int8_t>::stream(s, indent + "  ", v.estimation_done);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "initialized: ";
    Printer<int8_t>::stream(s, indent + "  ", v.initialized);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "anchor_offset: ";
    if (v.anchor_offset.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.anchor_offset.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.anchor_offset[i]);
    }
    if (v.anchor_offset.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_id: ";
    if (v.pose_id.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose_id.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.pose_id[i]);
    }
    if (v.pose_id.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estimate: ";
    if (v.estimate.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.estimate.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.estimate[i]);
    }
    if (v.estimate.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCL_SLAM_MESSAGE_NEIGHBOR_ESTIMATE_H
