// Generated by gencpp from file dcl_slam/uncertainty_point.msg
// DO NOT EDIT!


#ifndef DCL_SLAM_MESSAGE_UNCERTAINTY_POINT_H
#define DCL_SLAM_MESSAGE_UNCERTAINTY_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace dcl_slam
{
template <class ContainerAllocator>
struct uncertainty_point_
{
  typedef uncertainty_point_<ContainerAllocator> Type;

  uncertainty_point_()
    : position()
    , uncertainty_index(0.0)  {
    }
  uncertainty_point_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , uncertainty_index(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _uncertainty_index_type;
  _uncertainty_index_type uncertainty_index;





  typedef boost::shared_ptr< ::dcl_slam::uncertainty_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcl_slam::uncertainty_point_<ContainerAllocator> const> ConstPtr;

}; // struct uncertainty_point_

typedef ::dcl_slam::uncertainty_point_<std::allocator<void> > uncertainty_point;

typedef boost::shared_ptr< ::dcl_slam::uncertainty_point > uncertainty_pointPtr;
typedef boost::shared_ptr< ::dcl_slam::uncertainty_point const> uncertainty_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcl_slam::uncertainty_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcl_slam::uncertainty_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcl_slam::uncertainty_point_<ContainerAllocator1> & lhs, const ::dcl_slam::uncertainty_point_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.uncertainty_index == rhs.uncertainty_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcl_slam::uncertainty_point_<ContainerAllocator1> & lhs, const ::dcl_slam::uncertainty_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcl_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcl_slam::uncertainty_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcl_slam::uncertainty_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcl_slam::uncertainty_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b0f3eb68d085982d1550926c4bc6aa6";
  }

  static const char* value(const ::dcl_slam::uncertainty_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b0f3eb68d085982ULL;
  static const uint64_t static_value2 = 0xd1550926c4bc6aa6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcl_slam/uncertainty_point";
  }

  static const char* value(const ::dcl_slam::uncertainty_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float64 uncertainty_index\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dcl_slam::uncertainty_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.uncertainty_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uncertainty_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcl_slam::uncertainty_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcl_slam::uncertainty_point_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "uncertainty_index: ";
    Printer<double>::stream(s, indent + "  ", v.uncertainty_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCL_SLAM_MESSAGE_UNCERTAINTY_POINT_H
