# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dcl_slam/loop_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class loop_info(genpy.Message):
  _md5sum = "f1431bfa4497640b0a25a7c95cc6acc6"
  _type = "dcl_slam/loop_info"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Loop Info
Header header

int32 robot0
int32 robot1
int32 index0
int32 index1
float32 noise
int32 init_yaw
geometry_msgs/Transform pose0
geometry_msgs/Transform pose1
sensor_msgs/PointCloud2 scan_cloud
geometry_msgs/Transform pose_between
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field
"""
  __slots__ = ['header','robot0','robot1','index0','index1','noise','init_yaw','pose0','pose1','scan_cloud','pose_between']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','float32','int32','geometry_msgs/Transform','geometry_msgs/Transform','sensor_msgs/PointCloud2','geometry_msgs/Transform']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,robot0,robot1,index0,index1,noise,init_yaw,pose0,pose1,scan_cloud,pose_between

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(loop_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.robot0 is None:
        self.robot0 = 0
      if self.robot1 is None:
        self.robot1 = 0
      if self.index0 is None:
        self.index0 = 0
      if self.index1 is None:
        self.index1 = 0
      if self.noise is None:
        self.noise = 0.
      if self.init_yaw is None:
        self.init_yaw = 0
      if self.pose0 is None:
        self.pose0 = geometry_msgs.msg.Transform()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Transform()
      if self.scan_cloud is None:
        self.scan_cloud = sensor_msgs.msg.PointCloud2()
      if self.pose_between is None:
        self.pose_between = geometry_msgs.msg.Transform()
    else:
      self.header = std_msgs.msg.Header()
      self.robot0 = 0
      self.robot1 = 0
      self.index0 = 0
      self.index1 = 0
      self.noise = 0.
      self.init_yaw = 0
      self.pose0 = geometry_msgs.msg.Transform()
      self.pose1 = geometry_msgs.msg.Transform()
      self.scan_cloud = sensor_msgs.msg.PointCloud2()
      self.pose_between = geometry_msgs.msg.Transform()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4ifi14d3I().pack(_x.robot0, _x.robot1, _x.index0, _x.index1, _x.noise, _x.init_yaw, _x.pose0.translation.x, _x.pose0.translation.y, _x.pose0.translation.z, _x.pose0.rotation.x, _x.pose0.rotation.y, _x.pose0.rotation.z, _x.pose0.rotation.w, _x.pose1.translation.x, _x.pose1.translation.y, _x.pose1.translation.z, _x.pose1.rotation.x, _x.pose1.rotation.y, _x.pose1.rotation.z, _x.pose1.rotation.w, _x.scan_cloud.header.seq, _x.scan_cloud.header.stamp.secs, _x.scan_cloud.header.stamp.nsecs))
      _x = self.scan_cloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.scan_cloud.height, _x.scan_cloud.width))
      length = len(self.scan_cloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.scan_cloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.scan_cloud.is_bigendian, _x.scan_cloud.point_step, _x.scan_cloud.row_step))
      _x = self.scan_cloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7d().pack(_x.scan_cloud.is_dense, _x.pose_between.translation.x, _x.pose_between.translation.y, _x.pose_between.translation.z, _x.pose_between.rotation.x, _x.pose_between.rotation.y, _x.pose_between.rotation.z, _x.pose_between.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose0 is None:
        self.pose0 = geometry_msgs.msg.Transform()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Transform()
      if self.scan_cloud is None:
        self.scan_cloud = sensor_msgs.msg.PointCloud2()
      if self.pose_between is None:
        self.pose_between = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 148
      (_x.robot0, _x.robot1, _x.index0, _x.index1, _x.noise, _x.init_yaw, _x.pose0.translation.x, _x.pose0.translation.y, _x.pose0.translation.z, _x.pose0.rotation.x, _x.pose0.rotation.y, _x.pose0.rotation.z, _x.pose0.rotation.w, _x.pose1.translation.x, _x.pose1.translation.y, _x.pose1.translation.z, _x.pose1.rotation.x, _x.pose1.rotation.y, _x.pose1.rotation.z, _x.pose1.rotation.w, _x.scan_cloud.header.seq, _x.scan_cloud.header.stamp.secs, _x.scan_cloud.header.stamp.nsecs,) = _get_struct_4ifi14d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan_cloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.scan_cloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.scan_cloud.height, _x.scan_cloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scan_cloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.scan_cloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.scan_cloud.is_bigendian, _x.scan_cloud.point_step, _x.scan_cloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.scan_cloud.is_bigendian = bool(self.scan_cloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.scan_cloud.data = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.scan_cloud.is_dense, _x.pose_between.translation.x, _x.pose_between.translation.y, _x.pose_between.translation.z, _x.pose_between.rotation.x, _x.pose_between.rotation.y, _x.pose_between.rotation.z, _x.pose_between.rotation.w,) = _get_struct_B7d().unpack(str[start:end])
      self.scan_cloud.is_dense = bool(self.scan_cloud.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4ifi14d3I().pack(_x.robot0, _x.robot1, _x.index0, _x.index1, _x.noise, _x.init_yaw, _x.pose0.translation.x, _x.pose0.translation.y, _x.pose0.translation.z, _x.pose0.rotation.x, _x.pose0.rotation.y, _x.pose0.rotation.z, _x.pose0.rotation.w, _x.pose1.translation.x, _x.pose1.translation.y, _x.pose1.translation.z, _x.pose1.rotation.x, _x.pose1.rotation.y, _x.pose1.rotation.z, _x.pose1.rotation.w, _x.scan_cloud.header.seq, _x.scan_cloud.header.stamp.secs, _x.scan_cloud.header.stamp.nsecs))
      _x = self.scan_cloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.scan_cloud.height, _x.scan_cloud.width))
      length = len(self.scan_cloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.scan_cloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.scan_cloud.is_bigendian, _x.scan_cloud.point_step, _x.scan_cloud.row_step))
      _x = self.scan_cloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B7d().pack(_x.scan_cloud.is_dense, _x.pose_between.translation.x, _x.pose_between.translation.y, _x.pose_between.translation.z, _x.pose_between.rotation.x, _x.pose_between.rotation.y, _x.pose_between.rotation.z, _x.pose_between.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose0 is None:
        self.pose0 = geometry_msgs.msg.Transform()
      if self.pose1 is None:
        self.pose1 = geometry_msgs.msg.Transform()
      if self.scan_cloud is None:
        self.scan_cloud = sensor_msgs.msg.PointCloud2()
      if self.pose_between is None:
        self.pose_between = geometry_msgs.msg.Transform()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 148
      (_x.robot0, _x.robot1, _x.index0, _x.index1, _x.noise, _x.init_yaw, _x.pose0.translation.x, _x.pose0.translation.y, _x.pose0.translation.z, _x.pose0.rotation.x, _x.pose0.rotation.y, _x.pose0.rotation.z, _x.pose0.rotation.w, _x.pose1.translation.x, _x.pose1.translation.y, _x.pose1.translation.z, _x.pose1.rotation.x, _x.pose1.rotation.y, _x.pose1.rotation.z, _x.pose1.rotation.w, _x.scan_cloud.header.seq, _x.scan_cloud.header.stamp.secs, _x.scan_cloud.header.stamp.nsecs,) = _get_struct_4ifi14d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.scan_cloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.scan_cloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.scan_cloud.height, _x.scan_cloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scan_cloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.scan_cloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.scan_cloud.is_bigendian, _x.scan_cloud.point_step, _x.scan_cloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.scan_cloud.is_bigendian = bool(self.scan_cloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.scan_cloud.data = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.scan_cloud.is_dense, _x.pose_between.translation.x, _x.pose_between.translation.y, _x.pose_between.translation.z, _x.pose_between.rotation.x, _x.pose_between.rotation.y, _x.pose_between.rotation.z, _x.pose_between.rotation.w,) = _get_struct_B7d().unpack(str[start:end])
      self.scan_cloud.is_dense = bool(self.scan_cloud.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4ifi14d3I = None
def _get_struct_4ifi14d3I():
    global _struct_4ifi14d3I
    if _struct_4ifi14d3I is None:
        _struct_4ifi14d3I = struct.Struct("<4ifi14d3I")
    return _struct_4ifi14d3I
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_B7d = None
def _get_struct_B7d():
    global _struct_B7d
    if _struct_B7d is None:
        _struct_B7d = struct.Struct("<B7d")
    return _struct_B7d
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
